name: Windows
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16, 18, 20, 22, 23]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm test
